### ISSUE TITLE
Real world experiment set up

### ISSUE THREAD

**Issue by jacob-zietek** [google-research/language-table#19]
Hello LT authors!

Could you please share which mount and tool slide you use in your real-world experiment? I found the end effector in the paper appendix, but couldn't track down the details mentioned earlier.

I found something that looks similar (https://millibar.com/manual-tool-changer/), but I couldn't find a tool slide that the PVC pipe could screw into. I'd really appreciate your input!

Thank you,
Jacob

**Comment by ayzaan** [comment]
Hey @jacob-zietek. We have a custom millibar adapter that we 3d printed, which we use to attach the end effector to the arm.
Here is the STL file:
[millibar_adapter.zip](https://github.com/google-research/language-table/files/11657895/millibar_adapter.zip)
