### ISSUE TITLE
Access to text descriptions

### ISSUE THREAD

**Issue by krishanrana** [google-research/language-table#4]
Hi, I wanted to ask if it would be possible to get access to the raw text descriptions of the behaviors as opposed to the CLIP text embeddings?

**Comment by ayzaan** [comment]
Hi, the dataset actually does contain the raw text, they're encoded as bytes.
See the Loading Episodes example here: https://github.com/google-research/language-table/blob/main/language_table/examples/language_table_tutorial.ipynb

This is the function you can use to decode to a string. The notebook shows an example of this.
```
def decode_inst(inst):
  """Utility to decode encoded language instruction"""
  return bytes(inst[np.where(inst != 0)].tolist()).decode("utf-8") 
```

Let me know if this answers your question.

**Comment by krishanrana** [comment]
Sorry I missed that, this is exactly what I was looking for, thank you @ayzaan!
