### ISSUE TITLE
Colab broken since yesterday?

### ISSUE THREAD

**Issue by kpertsch** [google-research/language-table#6]
Hi!

I'm a big fan of this work and using it has been great!
However, I just noticed that the tutorial colab seems broken -- trying to execute it without change throws an error for me on the 3rd cell (where it tries to build the environment). 

<img width="1622" alt="image" src="https://user-images.githubusercontent.com/15955682/216743686-68225183-888a-4911-a1aa-fd6c2de37d12.png">

Apparently it does not download the `assets` folder correctly during installation for some reason, which is what's causing the error.

<img width="223" alt="image" src="https://user-images.githubusercontent.com/15955682/216743766-a0541c3e-d223-486d-b8e3-4f3c1e328b36.png">

This is a bit surprising since ~2 days ago the Colab worked without problem and it's not obvious how the new commit from yesterday would lead to the error. Curious whether you can reproduce the problem and have an idea what could be causing it!

Thanks,
Karl

**Comment by ayzaan** [comment]
Hey @kpertsch, thanks for reporting this. There was an issue in the setup script where non-python modules weren't getting copied, must've been exposed after a pip version upgrade on colab.

It should be fixed now!
